name: Matt Perger
favicon: null
layout_spectrum: 0.17809
typography_spectrum: 0.7237749474588782
title: Matt Perger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.5130996794905514
  saturation: 0.7596754126716405
  rhythmicContrast: 0.7082889948505908
purpose: []
